os:
  open: tmux-vim --no-tab {{filename}}
  openLink: xdg-open {{link}} >/dev/null 2>&1

customCommands:
  - key: 'q'
    description: 'Go back to nvim'
    context: 'global'
    command: 'tmux switch-client -t "$(tmux display-message -p "#S"):nvim"'
  - key: 'e'
    description: 'Edit file'
    context: 'files'
    command: tmux-vim --no-tab {{filename}}
  - key: 'o'
    description: 'Open file'
    context: 'files'
    command: 'tmux-vim --no-tab {{ .SelectedFile.Name }}'
  - key: 'o'
    description: 'Open file'
    context: 'staging'
    command: 'tmux-vim --no-tab {{ .SelectedFile.Name }}'

# contexts: status, files, localBranches, remotes, remoteBranches,
#           tags, commits, reflogCommits, subCommits, commitFiles,
#           stash, normal, merging, patchBuilding, staging, menu,
#           credentials, confirmation, search, commitMessage,
#           submodules, suggestions, cmdLog
