general.import = [ "~/.config/themes/current/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 12

[window]
padding.x = 0
padding.y = 0
decorations = "None"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = '''(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)//[a-zA-Z0-9,'+\.\-_/\?=&%:]+'''

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "S"
mode = "~Vi|~Search"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "SearchBackward"
key = "S"
mode = "~Vi"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "~Vi"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "PasteSelection"
key = "V"
mode = "~Vi"
mods = "Alt|Control"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b[13;2u"
