[icons]
chromium = ["chromium-work", "chromium-personal"]
firefox = ["firefox-work", "firefox-personal"]
godot=["nvim-godot"]
libreoffice-light=["libreoffice"]
prime-video=["primevideo"]
prusa-research=["prusa-slicer"]
rust-dark=[
  "rustc",
  "rustup",
  "rustdoc",
  "rust-analyzer",
  "rustfmt",
  "rust-gdb",
  "rust-lldb"
]
steam = ["steamos"]
vaultwarden-light=["vaultwarden-dmenu"]
vivaldi = [
  "vivaldi-work",
  "vivaldi-personal",
  "browser-work",
  "browser-personal"
]
discord = ["equibop"]
google-messages = ["kdeconnect-sms"]
windows-retro-light = ["windows"]
zohomail = ["email"]
