[packages]
paru = [
  "adwaita-dark",
  "age",
  "alacritty-sixel-git",
  "apg",
  "atool",
  "base-devel",
  "chafa",
  "cmake",
  "copyq",
  "dbus-broker",
  "dunst",
  "enca",
  "fakeroot",
  "gcc",
  "git",
  "glow",
  "gnome-keyring",
  "go",
  "grim",
  "gtk3-print-backends",
  "imagemagick",
  "inetutils",
  "inotify-tools",
  "jq",
  "kmonad-bin",
  "libpipewire",
  "libwireplumber",
  "lldb",
  "maim",
  "mpv",
  "mpv-mpris",
  "neomutt",
  "neovim-git",
  "network-manager-applet",
  "notmuch",
  "notmuch-runtime",
  "noto-fonts-emoji",
  "npm",
  "numlockx",
  "pandoc",
  "paru",
  "pipewire",
  "pkgconf",
  "playerctl",
  "polybar",
  "pulsemixer",
  "python",
  "python-black",
  "python-isort",
  "python-pip",
  "python-upnpclient",
  "qutebrowser",
  "ranger",
  "redshift",
  "ripgrep",
  "rofi",
  "ruby",
  "rustup",
  "shfmt",
  "slop",
  "slurp",
  "starship",
  "sway",
  "swayidle",
  "tmux",
  "udevil",
  "udisksvm",
  "unclutter",
  "w3m",
  "waybar",
  "wezterm",
  "wget",
  "which",
  "wireplumber",
  "wkhtmltopdf-static",
  "wl-clipboard",
  "wmctrl",
  "wob",
  "wofi",
  "wtype",
  "xcwd-git",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-kde",
  "xdg-desktop-portal-wlr",
  "xdotool",
  "xob",
  "xtitle",
  "yarn",
  "yt-dlp",
  "zenity",
]
go = [
  "github.com/pbogut/mails-go-web@latest"
]
