[packages]
paru = [
  "adwaita-dark",
  "age",
  "alacritty-sixel-git",
  "apg",
  "atool",
  "base-devel",
  "chafa",
  "cmake",
  "copyq",
  "dbus-broker",
  "ddcutil",
  "dunst",
  "enca",
  "fakeroot",
  "gcc",
  "git",
  "glow",
  "gnome-keyring",
  "go",
  "grim",
  "gtk3-print-backends",
  "hypridle",
  "hyprland",
  "hyprlock",
  "hyprpaper",
  "hyprpicker",
  "hyprpolkitagent",
  "i2c-tools",
  "imagemagick",
  "inetutils",
  "inotify-tools",
  "jq",
  "kmonad-bin",
  "libpam_pwdfile",
  "libpipewire",
  "libwireplumber",
  "lldb",
  "maim",
  "mise",
  "mpv",
  "mpv-mpris",
  "neomutt",
  "neovim",
  "network-manager-applet",
  "notmuch",
  "notmuch-runtime",
  "noto-fonts-emoji",
  "npm",
  "numlockx",
  "pandoc-bin",
  "paru",
  "pipewire",
  "pkgconf",
  "playerctl",
  "polybar",
  "pulsemixer",
  "python",
  "python-black",
  "python-isort",
  "python-pip",
  "python-upnpclient",
  "qutebrowser",
  "ranger",
  "redshift",
  "resvg",
  "ripgrep",
  "rofi",
  "ruby",
  "rustup",
  "satty",
  "shfmt",
  "slop",
  "slurp",
  "starship",
  "sway",
  "swayidle",
  "syncthing",
  "tmux",
  "udevil",
  "udisksvm",
  "unclutter",
  "w3m",
  "waybar",
  "wayfreeze",
  "wezterm-git",
  "wget",
  "which",
  "wiremix",
  "wireplumber",
  "wkhtmltopdf-static",
  "wl-clipboard",
  "wlsunset",
  "wmctrl",
  "wob",
  "wofi",
  "wtype",
  "xcwd-git",
  "xdg-desktop-portal",
  "xdg-desktop-portal-gtk",
  "xdg-desktop-portal-hyprland",
  "xdg-desktop-portal-kde",
  "xdg-desktop-portal-termfilechooser-boydaihungst-git",
  "xdg-desktop-portal-wlr",
  "xdotool",
  "xob",
  "xtitle",
  "yarn",
  "yazi",
  "yt-dlp",
  "zenity",
]
go = [
  "github.com/pbogut/audio-share-pc-client/audio-share-go-client@latest",
  "github.com/pbogut/go-serve@latest",
  "github.com/pbogut/hyprnotify@latest",
  "github.com/pbogut/mails-go-web@latest",
  "github.com/porjo/youtubeuploader@latest",
  "github.com/pbogut/systray-cli@latest",
]
cargo = [
  "bacon",
  "lsp-ai",
  "mprocs",
  "rtx-cli",
]
cargo_git = [
  "https://github.com/pbogut/enrichmail.git",
  "https://github.com/pbogut/cargo-workspace.git",
  "https://github.com/pbogut/rbw.git --branch add-uris-to-list",
]
